name: Image build and deploy to server
on:
  push:
    branches: [main]
jobs:
  build-docker-image:
    runs-on: ubuntu-latest
    outputs:
      image: ${{ fromJson(steps.build.outputs.metadata)['image.name'] }}
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - run: |
          echo "SHORTENED_SHA=${GITHUB_SHA:0:7}" >> $GITHUB_OUTPUT &&
          echo "REF_TAG=$(sed -e "s/\//\./g" <<< $REF_NAME)" >> $GITHUB_OUTPUT
        id: params
        env:
          GITHUB_SHA: ${{ github.sha }}
          REF_NAME: ${{ github.ref_name }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push
        id: build
        uses: docker/build-push-action@v5
        with:
          context: .
          build-args: |
            VITE_BASE_URL=${{ vars.VITE_BASE_URL }}
          push: true
          tags: ${{ vars.DOCKERHUB_USERNAME }}/${{ vars.IMAGE_NAME }}:${{ steps.params.outputs.REF_TAG }}-${{steps.params.outputs.SHORTENED_SHA}}

  request-deployment:
    needs: [build-docker-image]
    uses: CleverseAcademy/cd-compose-deployment/.github/workflows/deploy.yaml@main
    with:
      image: ${{ needs.build-docker-image.outputs.image }}
      service_name: ${{ vars.CD_SERVICE }}
    secrets:
      host: ${{ secrets.CD_HOST }}
      private_key: ${{ secrets.CD_CLI_PRIVATE_KEY_PEM }}
